package menu.util.options;

public enum Options {
    GET_ALL_STUDENTS, GET_ALL_GROUPS, GET_STUDENT_BY_ID, GET_GROUP_BY_ID
    , ADD_STUDENT, ADD_GROUP, UPDATE_STUDENT, UPDATE_GROUP, DELETE_STUDENT, DELETE_GROUP
    , STUDENT_EXIST, GET_ALL_STUDENTS_IN_GROUP, GET_ATTENDEES_IN_GROUP, GET_ONLINE_STUDENTS_IN_GROUP
    , GET_ALL_ATTENDEES_STUDENTS, GET_ALL_ONLINE_STUDENTS, GET_ALL_STIPENDS, GET_ALL_STUDENTS_WITH_PAYABLE_CONTRACT
    , GET_ALL_MALE_STUDENTS, GET_ALL_FEMALE_STUDENTS, GET_ALL_GROUPS_BY_LANGUAGE, GET_GROUPS_WITH_ONLINE_ACCESS
    , GET_FULL_GROUPS, GET_ALL_GROUPS_WITH_SAME_NAME
}
